all: modulePacker

modulePacker:
	@cd ModulePacker; make all
	@echo "\033[3;36m[Toolchain compiled]\033[0m"

clean:
	@cd ModulePacker; make clean
	@echo "\033[3;35m[Toolchain cleaned]\033[0m"


.PHONY: modulePacker all clean
